apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-depl
  template:
    metadata:
      labels:
        app: chart-depl
    spec:
      containers:
        - name: charts
          image: project-a/chart
          env:
            - name: MONGO_URI
              value: mongodb://charts-mongo-srv:27017/chart
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URI
              value: amqp://user:password@rabbitmq-srv:5672
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: chart-srv
spec:
  selector:
    app: chart-depl
  ports:
    - name: chart
      protocol: TCP
      port: 3000
      targetPort: 3000
