apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: project-a/order
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://order-mongo-srv:27017/order
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URL
              value: amqp://user:password@rabbitmq-srv:5672
            - name: REDIS_URI
              value: redis://redis-srv:6379
            - name: REDIS_URL_AUTH
              value: redis://auth-redis-srv:6379
---
apiVersion: v1
kind: Service
metadata:
  name: order-srv
spec:
  selector:
    app: order
  ports:
    - name: order
      protocol: TCP
      port: 3000
      targetPort: 3000