apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: project-a/payment
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://payment-mongo-srv:27017/payment
            - name: RABBITMQ_URI
              value: amqp://user:password@rabbitmq-srv:5672
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-publishable-key
                  key: STRIPE_PUBLISHABLE_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_SECRETS
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_SECRETS
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
