export enum Subject {
  OrderCreated = "order:created",
  OrderCancelled = "order:cancelled",
  PaymentCreated = "payment:created",
  PaymentSuccsess = "payment:succsess",
  PaymentCancelled = "payment:cancelled",
  LoginCreated = "login:created",
  NotifactionCreated = "notification:created",
  NotifactionCancelled = "notification:cancelled",
  ProductCreated = "product:created",
  ProductUpdated = "product:updated",
  ProductDeleted = "product:deleted",
  ExpirationComplete = "expiration:complete",
  MailSend = "mail:send",
  MailReceived = "mail:received",
  MailCancelled = "mail:cancelled",
  MailRead = "mail:read",
  MailDeleted = "mail:deleted",
  InvoiceCreated = "invoice:created",
}
